### ISSUE TITLE
Cannot Display Webserver on iOS Mobile Device

### ISSUE THREAD

**Issue by windynips** [ayushsharma82/ESP-DASH#16]
Greetings,
I cannot display the dash board on any iOS device.
Currently Running AP Example code, with the provided default ESP8266_SPIFFS_UPLOAD performed.

 I have tried, 3 iphones, all have safari and google chrome installed. I can connect to the webpage, it is not displaying anything. Android tablet running Google Chrome works perfectly.

**Comment by ayushsharma82** [comment]
I will check with my iPhone.

**Comment by ayushsharma82** [comment]
I can confirm that it's not working on safari or google chrome on Apple Devices. I will check if any fix is available.

**Comment by ayushsharma82** [comment]
Fixed in v2.1.0 - https://github.com/ayushsharma82/ESP-DASH/releases/tag/2.1.0

Thanks.

**Comment by ruddy17** [comment]
I pulled the recent version, but still can't open the dashboard on my iphone when serving from esp8266. Serving from dev environment from PC works.

**Comment by windynips** [comment]
I still have to check, i have been swamped with work. I will try and check
tonight or tomorrow

**Comment by ruddy17** [comment]
I managed to make it work. The problem was that I did not delete unnecessary .map and .js files from /dist, which were larger then my SPIFFS, and the app got truncated. Seems like your side is OK, though automatically cleaning /dist would be nice.
